global class SampleGlobalClass {
    global string name; //it is accessible outside of package or namespace or org
    public string description;
    private string privateDetails;

    //managed packaged means it cannot be changed. No one can see code. (.exe). App Exchange apps.
    //unmanage package. One can see code. (classes and files and other components are visible). Beta testing.

    //create unmanaged package first
        //create managed package from it.
}