List<integer> tempList = new list<integer>{5,21,15,99,77,101}; //this will add all these elements by default in the LIST.
integer sum1 = ListDemo2.add(tempList);
system.debug('sum1 is ' + sum1);


list<string> ls = new list<string> {'list', 'set', 'map', 'array'};
ls.add('methods');
ls.add('constructor');
system.debug(ListDemo2.add(ls));

ListDemo2.iterateListString(ls);


ListDemo2.iterateListString99();