set<integer> ns = new set<integer>();
ns.add(10);//will this work?

list<integer> l = new list<integer>();
boolean check = l.isEmpty();


string s = '';
s.toUpperCase();

integer i = 0;
system.debug(i+10);




SetDemo.citySet();

SetDemo.randomIntegerSet();

SetDemo.setFromList();

set<boolean> bs = new set<boolean>();
bs.add(true);
bs.add(false);
bs.add(null);
bs.add(true);
bs.add(false);
bs.add(null);
system.debug(bs);



SetDemo.upperCaseSet();

