//datatype  var name            value
//when we want to Define new variable
string      firstVariable =  'This is a first variable'; //defining a new variable
system.debug(firstVariable);


firstVariable = 'updating the variable value'; //yes, it will work.


system.debug('after update firstvarialbe ==> ' + firstVariable);

string secondVariable = 'this is a second variable';
system.debug('secondvariable ===>>> ' + secondVariable);
